service: ontimelog-scrapper-lambda
app: ontime-scrapper
org: roniemeque

frameworkVersion: "1"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  fetchStatus:
    handler: src/handler.fetchStatus
    timeout: 30
    maximumRetryAttempts: 1
    events:
      - http:
          path: fetchStatus
          method: post
  checkStatusUpdates:
    handler: src/rateHandler.checkStatusUpdates
    timeout: 30
    maximumRetryAttempts: 1
    events:
      - schedule: rate(30 minutes)
