version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0
  serverless: circleci/serverless-framework@1.0
jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Serverless Deploy
          command: sls deploy -v
workflows:
  deploy_workflow:
    jobs:
      - deploy
